### ISSUE TITLE
Art Gallery - comments

### ISSUE THREAD

**Issue by ngokevin** [darkwing/aframe-blog-posts#2]
Nice introductory guide. Some comments:
- The easiness of richness interactivity in the first paragraph is somewhat misleading. It is possible to do interactivity without writing JavaScript, but mostly with the help of third-party components. It sounds like A-Frame actively avoids JavaScript when it integrates well with it. It sounds like we provide an out-of-the-box way for richness and interactivity, but we mostly provide a framework for it (vs. a library). Perhaps I'd reserve these points when we produce an example that has interactivity since the Art Gallery doesn't. Perhaps there should be a part 2 of this example that loads dynamically loads images from Flickr based on user album selection.
- Need to mention the imposter syndrome with the first two sentences? First two sentences are critical for first impression and getting an idea of the key points.
- I'd rename WSAD to the more commonly referred WASD (which is also in the name of the component that provides it).
- Perhaps it should mention how you could actually _walk_ (e.g., Vive) around to hit the point that it's for VR first.

**Comment by darkwing** [comment]
I definitely want this to be the first of a series of posts.  I'd like to add the following in a second post:
-  Add lighting
-  Add cursor+fuse to do something with the image
-  Add sound
-  Add animation
-  Add more components

More ideas include:
-  Add physics so people can't walk through the walls
-  Add a few pillars in the room, add physics so they can't walk through them
-  Add text using @ngokevin's lib
-  Dynamically add images to the gallery (from Flickr, wherever)

There are many possibilities!  Thank you for the feedback!

**Comment by darkwing** [comment]
Fixed in https://github.com/darkwing/aframe-blog-posts/commit/75103f2e9b870d6d42660c67a105a4cf30d418ab
